version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dishdiary
    networks:
      - dishdiary-net

  dishdiary-app:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/dishdiary
      - DATABASE_USERNAME=docker
      - DATABASE_PASSWORD=docker
      - SALT_KEY=cmFua19yYW5nb19mcm5k
    ports:
      - '8080:8080'
    networks:
      - dishdiary-net

networks:
  dishdiary-net:
    driver: bridge
